#Following are scheduler for crontab.

data_extractor_job:
  cron: "* * * * *" #Every two min.
  class: "DataExtractor"


# data_storage_job:
#   cron: "* * * * *" #Every two min.
#   class: "DataStorage"  